[package]
name = "lr-gen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.2.6"
xml-w3c = { version = "0.1.0", path = "../xml-w3c" }

[dev-dependencies]
stable-eyre = "0.2.2"
